# Generated by Django 4.2.1 on 2023-05-16 11:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1, editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expenses",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1, editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="income",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1, editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
    ]
