# Generated by Django 4.2.1 on 2023-05-13 11:07

import autoslug.fields
from django.db import migrations
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_field_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=main_app.models.slugify_two_fields, unique=True, verbose_name='slug'),
        ),
    ]
