# Generated by Django 4.2.1 on 2023-05-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_branch_slug_alter_field_slug_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='main_app.branch', verbose_name='Filial'),
        ),
    ]
