# Generated by Django 4.2.1 on 2023-05-13 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0004_alter_room_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Vazifasi')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism Familiyasi')),
                ('phone_number', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamingiz + yoki 9 bilan boshlanishi va 12 belgidan oshmasligi lozim. Masalan: +998991271405', regex='^[\\+]?[(]?[8-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='Telefon raqami')),
                ('passport', models.CharField(max_length=15, unique=True, verbose_name='Passport raqami')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maosh')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='userapp.role', verbose_name='Vazifasi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism va Familyasi')),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('passport', models.CharField(max_length=15, unique=True, verbose_name='Passport raqami')),
                ('phone_number', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamingiz + yoki 9 bilan boshlanishi va 12 belgidan oshmasligi lozim. Masalan: +998991271405', regex='^[\\+]?[(]?[8-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='Telefon raqami')),
                ('parents_name', models.CharField(max_length=100, verbose_name='Ota-onasining ismi')),
                ('parents_phone_number', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamingiz + yoki 9 bilan boshlanishi va 12 belgidan oshmasligi lozim. Masalan: +998991271405', regex='^[\\+]?[(]?[8-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='Ota-onasining telefon raqami')),
                ('day', models.CharField(choices=[('toq', 'Du-Chor-Jum'), ('juft', 'Se-Pay-Shan'), ('boot', 'Bootcamp')], default='toq', max_length=25, verbose_name='Kurs kunlari')),
                ('time', models.CharField(choices=[('8', '8:00-11:00'), ('12', '12:00-14:00'), ('14', '14:00-17:00'), ('17', '17:00-20:00')], default='8', max_length=25, verbose_name='Kurs vaqtlari')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main_app.field', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
