# Generated by Django 4.2.1 on 2023-05-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_room_branch'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-created_at',), 'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
        migrations.AddField(
            model_name='worker',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='main_app.field', verbose_name="O'qituvchi yo'nalishi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="O'qituvchi foizi"),
        ),
    ]
